"""Writing the outputs: a two-layer .pyz (the default), a directory, or an AWS Lambda zip.

Layout of the output (see docs/adr/0010-bundle-format-and-loader.md):

    #!/usr/bin/env python3
    zip:
      payload.zip    stored, not compressed: the installed packages (itself a deflated zip)
      __main__.py    the loader (_loader.py with its config filled in)
      __main__.pyc   the loader compiled for the target Python, so it isn't recompiled on each run
      manifest.json  what's inside, with hashes (`bundleup verify`)

For several platforms or Python versions (ADR-0038), `layer-<hash>.zip` members replace
payload.zip: each file is stored once, in the layer of the payloads that have it, and each
payload unpacks its layers in order.
"""

from __future__ import annotations

import hashlib
import json
import os
import shutil
import zipfile
from collections.abc import Iterable
from pathlib import Path

from . import __version__, _bytecode, _verify
from ._errors import (
    BundleupError,
    CheckFailedError,
    Diagnostic,
    UsageError,
)
from ._formats import Format, describe_size
from ._payload import (
    COMPILE_ENV,
    Entry,
    Layer,
    Prepared,
    pth_files,
    runtime_needs,
    verify_payload,
    write_layers,
    write_payload,
)
from ._python import Portability, PythonRange, Target
from ._source import Source, safe_name
from ._steps import Progress, Steps, run
from ._text import findings

LOADER = Path(__file__).with_name("_loader.py")
MANIFEST = "manifest.json"  # in the outer zip, next to __main__.py
FIXED_TIME = (1980, 1, 1, 0, 0, 0)  # reproducible zips: same inputs, same bytes, same cache key
COMPILE_LOADER = """
import py_compile, sys
py_compile.compile(sys.argv[1], cfile=sys.argv[2], dfile="__main__.py", doraise=True,
                   invalidation_mode=py_compile.PycInvalidationMode.UNCHECKED_HASH)
"""


def render_loader(config: dict[str, object]) -> str:
    """The loader's source with its config block replaced by this bundle's values."""
    text = LOADER.read_text(encoding="utf-8")
    head, rest = text.split("# --- config: replaced at build time ---\n", 1)
    _, tail = rest.split("# --- end config ---\n", 1)
    lines = "".join(f"{k} = {v!r}\n" for k, v in config.items())
    return f"{head}# --- config (generated by bundleup) ---\n{lines}# --- end config ---\n{tail}"


def manifest(
    *,
    source: Source,
    version: str | None,
    target: Target,
    native: bool,
    entry: Entry | None,
    cache_dir: str | None,
    fmt: Format,
    payload: Path | None,
    payload_sha256: str | None,
    locked: list[_verify.LockedPackage],
    files: dict[str, str],
    loader: dict[str, str] | None,
    pythons: PythonRange,
    reach: Portability,
) -> bytes:
    """What's inside the bundle, with hashes: read by `bundleup verify` and by reviewers
    (`unzip -p app.pyz manifest.json`). Sorted, so the same inputs give the same bytes."""
    document = {
        "manifest_version": 1,
        "bundleup_version": __version__,
        "name": source.name,
        "version": version,
        "target": target.to_json_dict(native=native, pythons=pythons, reach=reach),
        "entry": list(entry) if entry else None,
        "cache_dir": cache_dir,
        "format": fmt,
        # The inner zip and the loader exist only in a .pyz; `files` covers every format.
        "payload": {"sha256": payload_sha256, "size": payload.stat().st_size} if payload else None,
        "loader": loader,  # __main__.py and __main__.pyc: they run first, so they're checked too
        "packages": [
            {"name": p.name, "version": p.version} for p in sorted(locked, key=lambda p: p.name)
        ],
        "files": files,
    }
    return json.dumps(document, indent=1, sort_keys=True).encode("utf-8") + b"\n"


def write_bundle(
    output: Path,
    *,
    payloads: dict[str, Path],
    loader: Path,
    loader_pyc: Path,
    manifest_json: bytes,
) -> None:
    """Write shebang + outer zip to a temporary file, then rename it over `output`. `payloads`:
    member name -> payload zip (one, `payload.zip`, unless the bundle is for several platforms)."""
    output.parent.mkdir(parents=True, exist_ok=True)
    tmp = output.with_name(f".{output.name}.tmp-{os.getpid()}")
    try:
        with open(tmp, "wb") as f:
            # Plain python3 (works everywhere, also with Windows' py launcher); a wrong version
            # re-runs itself with a matching one (ADR-0036).
            f.write(b"#!/usr/bin/env python3\n")
            with zipfile.ZipFile(f, "w", zipfile.ZIP_STORED) as zf:
                for member, payload in sorted(payloads.items()):
                    info = zipfile.ZipInfo(member, FIXED_TIME)
                    info.external_attr = 0o100644 << 16
                    big = payload.stat().st_size > 0x7FFFFFFF
                    with open(payload, "rb") as src, zf.open(info, "w", force_zip64=big) as dest:
                        shutil.copyfileobj(src, dest, 1 << 20)
                for path, name in ((loader, "__main__.py"), (loader_pyc, "__main__.pyc")):
                    info = zipfile.ZipInfo(name, FIXED_TIME)
                    info.external_attr = 0o100644 << 16
                    zf.writestr(info, path.read_bytes())
                info = zipfile.ZipInfo(MANIFEST, FIXED_TIME)
                info.external_attr = 0o100644 << 16
                info.compress_type = zipfile.ZIP_DEFLATED  # can be MBs for big bundles
                zf.writestr(info, manifest_json)
        tmp.chmod(0o755)
        tmp.replace(output)
    finally:
        if tmp.exists():
            tmp.unlink()


DIR_MANIFEST = "bundleup-manifest.json"  # in a `dir` output and at the top of a Lambda zip
# AWS Lambda's limits for a function's .zip (checked 2026-10-05): 50 MB to upload directly,
# 250 MB unzipped including layers.
LAMBDA_UPLOAD = 50 * 1000 * 1000
LAMBDA_UNZIPPED = 250 * 1000 * 1000


def lambda_upload_warning(output: Path) -> Diagnostic:
    return Diagnostic(
        "lambda-upload-size",
        "warning",
        f"{output.name} is over Lambda's 50 MB limit for uploading a .zip directly",
        hint="upload it to S3 and point the function at it (the limit there is 250 MB unzipped), "
        "or move large dependencies into a layer",
    )


def _loader_settings(p: Prepared, *, members: list[str], dirname: str) -> dict[str, object]:
    """What the loader needs to know about one payload (its config, or one PAYLOADS entry)."""
    target, native = p.target, p.native
    needs = runtime_needs(p.site)
    return {
        "dirname": dirname,
        "members": members,
        "python": p.pythons.min,
        "python_max": p.pythons.max,
        "platform": None if p.reach.any_os else target.platform,  # None: any OS (ADR-0034)
        "machine": target.machine if native or not p.reach.any_cpu else None,
        "abiflags": target.abiflags if native else None,
        "target": target.describe(native, p.pythons, p.reach),
        "pth": pth_files(p.site),
        "libc": needs.libc if native else None,
        "macos": needs.macos if native else None,
    }


def write_pyz(
    ps: list[Prepared],
    output: Path,
    *,
    stage: Path,
    steps: Steps,
    progress: Progress,
    max_size: int | None = None,
) -> list[Diagnostic]:
    """The default: shebang + outer zip with the loader, the manifest and the payload, or one
    payload per platform and Python version when there are several (ADR-0038). Refuses, before
    writing, a bundle over `max_size` bytes (ADR-0039)."""
    first = ps[0]
    assert first.entry is not None  # resolved for every .pyz
    name = safe_name(first.source.name)
    steps.start("zip")
    if len(ps) == 1:
        staged = stage / "payload.zip"
        digest, written = write_payload(first.site, staged)
        layers = [Layer("payload.zip", staged, digest, written, (0,))]
    else:
        layers = write_layers([p.site for p in ps], stage)
    total = sum(layer.path.stat().st_size for layer in layers)
    diags: list[Diagnostic] = []
    check_size(total, max_size, diags)
    if max_size is None and total > LARGE:
        diags.append(_large(total, ps))
    steps.start("verify")
    mine = [[layer for layer in layers if i in layer.owners] for i in range(len(ps))]
    files = [{rel: h for layer in own for rel, h in layer.files.items()} for own in mine]
    locked = [
        verify_payload(
            p.site, pylock=p.pylock, target=p.target, written=written, script=p.script, own=p.own
        )
        for p, written in zip(ps, files)
    ]
    steps.start("write")
    settings = []
    for p, own in zip(ps, mine):
        # A payload's unpacked copy is named after its contents: its layers' hashes.
        digest = own[0].digest if len(ps) == 1 else _combined(layer.digest for layer in own)
        members = [layer.member for layer in own]
        settings.append(_loader_settings(p, members=members, dirname=f"{name}-{digest[:16]}"))
    main = settings[0]
    config = {
        "NAME": first.source.name,
        "DIRNAME": main["dirname"],
        "PYTHON": main["python"],
        "PYTHON_MAX": main["python_max"],
        "PLATFORM": main["platform"],
        "MACHINE": main["machine"],
        "ABIFLAGS": main["abiflags"],
        "TARGET": main["target"],
        "ENTRY": tuple(first.entry),  # a plain tuple: the loader reads its repr
        "PTH": main["pth"],
        "LIBC": main["libc"],
        "MACOS": main["macos"],
        "MEMBERS": main["members"],
        "PAYLOADS": settings if len(ps) > 1 else [],
    }
    loader, loader_pyc = stage / "__main__.py", stage / "__main__.pyc"
    loader.write_text(render_loader(config), encoding="utf-8")
    run(
        [first.target.executable, "-I", "-c", COMPILE_LOADER, str(loader), str(loader_pyc)],
        what="compiling the loader",
        progress=progress,
        error=BundleupError,
        env=COMPILE_ENV,
    )
    hashes = {
        "__main__.py": _verify.record_hash(loader.read_bytes()),
        "__main__.pyc": _verify.record_hash(loader_pyc.read_bytes()),
    }
    if len(ps) == 1:
        p, (layer,) = first, layers
        manifest_json = manifest(
            source=p.source,
            version=p.version,
            target=p.target,
            native=p.native,
            entry=p.entry,
            cache_dir=str(main["dirname"]),
            fmt="pyz",
            payload=layer.path,
            payload_sha256=layer.digest,
            locked=locked[0],
            files=layer.files,
            loader=hashes,
            pythons=p.pythons,
            reach=p.reach,
        )
    else:
        manifest_json = _multi_manifest(ps, layers, settings, locked, hashes)
    payloads = {layer.member: layer.path for layer in layers}
    write_bundle(
        output, payloads=payloads, loader=loader, loader_pyc=loader_pyc, manifest_json=manifest_json
    )
    return diags


def _combined(digests: Iterable[str]) -> str:
    return hashlib.sha256("".join(digests).encode()).hexdigest()


def _multi_manifest(
    ps: list[Prepared],
    layers: list[Layer],
    settings: list[dict[str, object]],
    locked: list[list[_verify.LockedPackage]],
    loader: dict[str, str],
) -> bytes:
    """The manifest of a bundle for several platforms: the shared fields once, each layer with
    its hash and files, then each payload with its layers, target and packages (ADR-0038)."""
    first = ps[0]
    payloads = []
    for p, entry, packages in zip(ps, settings, locked):
        payloads.append(
            {
                "members": entry["members"],
                "cache_dir": entry["dirname"],
                "target": p.target.to_json_dict(native=p.native, pythons=p.pythons, reach=p.reach),
                "packages": [
                    {"name": x.name, "version": x.version}
                    for x in sorted(packages, key=lambda x: x.name)
                ],
            }
        )
    document = {
        "manifest_version": 1,
        "bundleup_version": __version__,
        "name": first.source.name,
        "version": first.version,
        "entry": list(first.entry) if first.entry else None,
        "format": "pyz",
        "loader": loader,
        "layers": {
            layer.member: {
                "sha256": layer.digest,
                "size": layer.path.stat().st_size,
                "files": layer.files,
            }
            for layer in layers
        },
        "payloads": payloads,
    }
    return json.dumps(document, indent=1, sort_keys=True).encode("utf-8") + b"\n"


def _plain_manifest(p: Prepared, fmt: Format, written: dict[str, str]) -> bytes:
    locked = verify_payload(
        p.site, pylock=p.pylock, target=p.target, written=written, script=p.script, own=p.own
    )
    return manifest(
        source=p.source,
        version=p.version,
        target=p.target,
        native=p.native,
        entry=p.entry,
        cache_dir=None,
        fmt=fmt,
        payload=None,
        payload_sha256=None,
        locked=locked,
        files=written,
        loader=None,
        pythons=p.pythons,
        reach=p.reach,
    )


def write_dir(p: Prepared, output: Path, *, steps: Steps) -> None:
    """The payload as a plain directory, for hosts that put a directory on sys.path (Splunk's
    bin/lib, QGIS, Azure Functions' .python_packages). Replaces an earlier bundleup output
    atomically; refuses to replace anything else."""
    steps.start("verify")
    written = {
        rel: _verify.record_hash(Path(path).read_bytes())
        for rel, path in _bytecode.walk_files(p.site)
    }
    manifest_json = _plain_manifest(p, "dir", written)
    steps.start("write")
    if output.exists() and not (
        output.is_dir() and (not any(output.iterdir()) or (output / DIR_MANIFEST).is_file())
    ):
        raise UsageError(
            f"{output} already exists and isn't a directory bundleup wrote",
            hint="remove it, or choose another place with -o",
        )
    output.parent.mkdir(parents=True, exist_ok=True)
    tmp = output.with_name(f".{output.name}.tmp-{os.getpid()}")
    old = output.with_name(f".{output.name}.old-{os.getpid()}")
    try:
        shutil.copytree(p.site, tmp, symlinks=True)
        (tmp / DIR_MANIFEST).write_bytes(manifest_json)
        if output.exists():
            output.rename(old)
        tmp.rename(output)
    finally:
        shutil.rmtree(tmp, ignore_errors=True)
        shutil.rmtree(old, ignore_errors=True)


def stage_lambda(p: Prepared, *, stage: Path, steps: Steps) -> Path:
    """An AWS Lambda function .zip, in the staging directory: the packages and the project at the
    top (Lambda puts /var/task on sys.path), bytecode precompiled for the runtime's Python, since
    /var/task is read-only; the manifest alongside."""
    steps.start("zip")
    staged = stage / "lambda.zip"
    _digest, written = write_payload(p.site, staged)
    steps.start("verify")
    manifest_json = _plain_manifest(p, "lambda", written)
    steps.start("write")
    with zipfile.ZipFile(staged, "a") as zf:
        info = zipfile.ZipInfo(DIR_MANIFEST, FIXED_TIME)
        info.external_attr = 0o100644 << 16
        info.compress_type = zipfile.ZIP_DEFLATED
        zf.writestr(info, manifest_json)
    return staged


# GitHub refuses files over 100 MB, so a repository, or a skill installed from one, can't hold a
# bigger bundle without Git LFS (docs.github.com, "About large files on GitHub", 2026-10-07).
LARGE = 100 * 10**6


def _large(total: int, ps: list[Prepared]) -> Diagnostic:
    """A warning for a bundle too big for a git repository, saying where the size comes from."""
    largest = ", ".join(f"{x.name} {describe_size(x.size_bytes)}" for x in ps[0].sizes[:3])
    each = f" in each of the {len(ps)} payloads" if len(ps) > 1 else ""
    return Diagnostic(
        "large-bundle",
        "warning",
        f"the bundle is {describe_size(total)}: GitHub refuses files over 100 MB, so a "
        "repository (or a skill installed from one) can't hold it without Git LFS",
        hint=f"the largest packages{each} (unpacked): {largest}; fewer --python or "
        "--python-platform values make it smaller, and --max-size makes a limit an error",
    )


def check_size(size: int, max_size: int | None, diagnostics: list[Diagnostic]) -> None:
    """Refuse, before anything is written, an output bigger than --max-size (ADR-0039)."""
    if max_size is None or size <= max_size:
        return
    diagnostics.append(
        Diagnostic(
            "max-size",
            "error",
            f"the output would be {describe_size(size)}, over --max-size {describe_size(max_size)}",
            hint="`bundleup check -v` lists the largest packages",
        )
    )
    errors = sum(d.level == "error" for d in diagnostics)
    raise CheckFailedError(
        f"found {findings(errors, len(diagnostics) - errors)}, so nothing was written",
        diagnostics=diagnostics,
    )
