"""Writing the outputs: a two-layer .pyz (the default), a directory, or an AWS Lambda zip.

Layout of the output (see docs/adr/0010-bundle-format-and-loader.md):

    #!/usr/bin/env python3
    zip:
      payload.zip    stored, not compressed: the installed packages (itself a deflated zip)
      __main__.py    the loader (_loader.py with its config filled in)
      __main__.pyc   the loader compiled for the target Python, so it isn't recompiled on each run
"""

from __future__ import annotations

import json
import os
import shutil
import zipfile
from pathlib import Path

from . import __version__, _bytecode, _verify
from ._errors import (
    BundleupError,
    CheckFailedError,
    Diagnostic,
    UsageError,
)
from ._payload import (
    COMPILE_ENV,
    Entry,
    Prepared,
    pth_files,
    runtime_needs,
    verify_payload,
    write_payload,
)
from ._python import Portability, PythonRange, Target
from ._source import Source, safe_name
from ._steps import Progress, Steps, run
from ._targets import Format

LOADER = Path(__file__).with_name("_loader.py")
MANIFEST = "manifest.json"  # in the outer zip, next to __main__.py
FIXED_TIME = (1980, 1, 1, 0, 0, 0)  # reproducible zips: same inputs, same bytes, same cache key
COMPILE_LOADER = """
import py_compile, sys
py_compile.compile(sys.argv[1], cfile=sys.argv[2], dfile="__main__.py", doraise=True,
                   invalidation_mode=py_compile.PycInvalidationMode.UNCHECKED_HASH)
"""


def render_loader(config: dict[str, object]) -> str:
    """The loader's source with its config block replaced by this bundle's values."""
    text = LOADER.read_text(encoding="utf-8")
    head, rest = text.split("# --- config: replaced at build time ---\n", 1)
    _, tail = rest.split("# --- end config ---\n", 1)
    lines = "".join(f"{k} = {v!r}\n" for k, v in config.items())
    return f"{head}# --- config (generated by bundleup) ---\n{lines}# --- end config ---\n{tail}"


def manifest(
    *,
    source: Source,
    version: str | None,
    target: Target,
    native: bool,
    entry: Entry | None,
    cache_dir: str | None,
    fmt: Format,
    payload: Path | None,
    payload_sha256: str | None,
    locked: list[_verify.LockedPackage],
    files: dict[str, str],
    loader: dict[str, str] | None,
    pythons: PythonRange,
    reach: Portability,
) -> bytes:
    """What's inside the bundle, with hashes: read by `bundleup verify` and by reviewers
    (`unzip -p app.pyz manifest.json`). Sorted, so the same inputs give the same bytes."""
    document = {
        "manifest_version": 1,
        "bundleup_version": __version__,
        "name": source.name,
        "version": version,
        "target": target.to_json_dict(native=native, pythons=pythons, reach=reach),
        "entry": list(entry) if entry else None,
        "cache_dir": cache_dir,
        "format": fmt,
        # The inner zip and the loader exist only in a .pyz; `files` covers every format.
        "payload": {"sha256": payload_sha256, "size": payload.stat().st_size} if payload else None,
        "loader": loader,  # __main__.py and __main__.pyc: they run first, so they're checked too
        "packages": [
            {"name": p.name, "version": p.version} for p in sorted(locked, key=lambda p: p.name)
        ],
        "files": files,
    }
    return json.dumps(document, indent=1, sort_keys=True).encode("utf-8") + b"\n"


def write_bundle(
    output: Path,
    *,
    payload: Path,
    loader: Path,
    loader_pyc: Path,
    manifest_json: bytes,
    pythons: PythonRange,
) -> None:
    """Write shebang + outer zip to a temporary file, then rename it over `output`. The shebang
    names the version when the bundle runs on only one (`./app.pyz` then finds the right Python,
    and Windows' py launcher reads it too); otherwise plain python3 (ADR-0030)."""
    output.parent.mkdir(parents=True, exist_ok=True)
    tmp = output.with_name(f".{output.name}.tmp-{os.getpid()}")
    try:
        with open(tmp, "wb") as f:
            python = f"python{pythons.min[0]}.{pythons.min[1]}" if pythons.exact else "python3"
            f.write(f"#!/usr/bin/env {python}\n".encode())
            with zipfile.ZipFile(f, "w", zipfile.ZIP_STORED) as zf:
                info = zipfile.ZipInfo("payload.zip", FIXED_TIME)
                info.external_attr = 0o100644 << 16
                with (
                    open(payload, "rb") as src,
                    zf.open(info, "w", force_zip64=payload.stat().st_size > 0x7FFFFFFF) as dest,
                ):
                    shutil.copyfileobj(src, dest, 1 << 20)
                for path, name in ((loader, "__main__.py"), (loader_pyc, "__main__.pyc")):
                    info = zipfile.ZipInfo(name, FIXED_TIME)
                    info.external_attr = 0o100644 << 16
                    zf.writestr(info, path.read_bytes())
                info = zipfile.ZipInfo(MANIFEST, FIXED_TIME)
                info.external_attr = 0o100644 << 16
                info.compress_type = zipfile.ZIP_DEFLATED  # can be MBs for big bundles
                zf.writestr(info, manifest_json)
        tmp.chmod(0o755)
        tmp.replace(output)
    finally:
        if tmp.exists():
            tmp.unlink()


DIR_MANIFEST = "bundleup-manifest.json"  # in a `dir` output and at the top of a Lambda zip
# AWS Lambda's limits for a function's .zip (checked 2026-10-05): 50 MB to upload directly,
# 250 MB unzipped including layers.
LAMBDA_UPLOAD = 50 * 1000 * 1000
LAMBDA_UNZIPPED = 250 * 1000 * 1000


def lambda_upload_warning(output: Path) -> Diagnostic:
    return Diagnostic(
        "lambda-upload-size",
        "warning",
        f"{output.name} is over Lambda's 50 MB limit for uploading a .zip directly",
        hint="upload it to S3 and point the function at it (the limit there is 250 MB unzipped), "
        "or move large dependencies into a layer",
    )


def write_pyz(
    p: Prepared,
    output: Path,
    *,
    stage: Path,
    steps: Steps,
    progress: Progress,
    size_limit: tuple[int, str] | None = None,
    strict: bool = False,
) -> list[Diagnostic]:
    """The default: shebang + outer zip with the loader, the manifest and the payload. With a
    destination's `size_limit` (a preset's), warns when the bundle is over it, and refuses before
    writing under `strict`."""
    assert p.entry is not None  # resolved for every .pyz
    steps.start("zip")
    payload = stage / "payload.zip"
    digest, written = write_payload(p.site, payload)
    diags = []
    if size_limit and payload.stat().st_size > size_limit[0]:
        limit, what = size_limit
        diags.append(
            Diagnostic(
                "size-limit",
                "warning",
                f"the bundle is {payload.stat().st_size / 1e6:.0f} MB, over {what} "
                f"({limit / 1e6:.0f} MB)",
                hint="`bundleup check -v` lists the largest packages",
            )
        )
        if strict:
            raise CheckFailedError(
                "found 1 warning, so nothing was written",
                diagnostics=diags,
                hint="--strict makes warnings fail too; build without it to allow them",
            )
    steps.start("verify")
    locked = verify_payload(
        p.site, pylock=p.pylock, target=p.target, written=written, script=p.script
    )
    steps.start("write")
    cache_dir = f"{safe_name(p.source.name)}-{digest[:16]}"
    target, native = p.target, p.native
    needs = runtime_needs(p.site)
    config = {
        "NAME": p.source.name,
        "DIRNAME": cache_dir,
        "PYTHON": p.pythons.min,
        "PYTHON_MAX": p.pythons.max,
        "PLATFORM": None if p.reach.any_os else target.platform,  # None: any OS (ADR-0034)
        "MACHINE": target.machine if native or not p.reach.any_cpu else None,
        "ABIFLAGS": target.abiflags if native else None,
        "TARGET": target.describe(native, p.pythons, p.reach),
        "ENTRY": tuple(p.entry),  # a plain tuple: the loader reads its repr
        "PTH": pth_files(p.site),
        "LIBC": needs.libc if native else None,
        "MACOS": needs.macos if native else None,
    }
    loader, loader_pyc = stage / "__main__.py", stage / "__main__.pyc"
    loader.write_text(render_loader(config), encoding="utf-8")
    run(
        [target.executable, "-I", "-c", COMPILE_LOADER, str(loader), str(loader_pyc)],
        what="compiling the loader",
        progress=progress,
        error=BundleupError,
        env=COMPILE_ENV,
    )
    manifest_json = manifest(
        source=p.source,
        version=p.version,
        target=target,
        native=native,
        entry=p.entry,
        cache_dir=cache_dir,
        fmt="pyz",
        payload=payload,
        payload_sha256=digest,
        locked=locked,
        files=written,
        loader={
            "__main__.py": _verify.record_hash(loader.read_bytes()),
            "__main__.pyc": _verify.record_hash(loader_pyc.read_bytes()),
        },
        pythons=p.pythons,
        reach=p.reach,
    )
    write_bundle(
        output,
        payload=payload,
        loader=loader,
        loader_pyc=loader_pyc,
        manifest_json=manifest_json,
        pythons=p.pythons,
    )
    return diags


def _plain_manifest(p: Prepared, fmt: Format, written: dict[str, str]) -> bytes:
    locked = verify_payload(
        p.site, pylock=p.pylock, target=p.target, written=written, script=p.script
    )
    return manifest(
        source=p.source,
        version=p.version,
        target=p.target,
        native=p.native,
        entry=p.entry,
        cache_dir=None,
        fmt=fmt,
        payload=None,
        payload_sha256=None,
        locked=locked,
        files=written,
        loader=None,
        pythons=p.pythons,
        reach=p.reach,
    )


def write_dir(p: Prepared, output: Path, *, steps: Steps) -> None:
    """The payload as a plain directory, for hosts that put a directory on sys.path (Splunk's
    bin/lib, QGIS, Azure Functions' .python_packages). Replaces an earlier bundleup output
    atomically; refuses to replace anything else."""
    steps.start("verify")
    written = {
        rel: _verify.record_hash(Path(path).read_bytes())
        for rel, path in _bytecode.walk_files(p.site)
    }
    manifest_json = _plain_manifest(p, "dir", written)
    steps.start("write")
    if output.exists() and not (
        output.is_dir() and (not any(output.iterdir()) or (output / DIR_MANIFEST).is_file())
    ):
        raise UsageError(
            f"{output} already exists and isn't a directory bundleup wrote",
            hint="remove it, or choose another place with -o",
        )
    output.parent.mkdir(parents=True, exist_ok=True)
    tmp = output.with_name(f".{output.name}.tmp-{os.getpid()}")
    old = output.with_name(f".{output.name}.old-{os.getpid()}")
    try:
        shutil.copytree(p.site, tmp, symlinks=True)
        (tmp / DIR_MANIFEST).write_bytes(manifest_json)
        if output.exists():
            output.rename(old)
        tmp.rename(output)
    finally:
        shutil.rmtree(tmp, ignore_errors=True)
        shutil.rmtree(old, ignore_errors=True)


def stage_lambda(p: Prepared, *, stage: Path, steps: Steps) -> Path:
    """An AWS Lambda function .zip, in the staging directory: the packages and the project at the
    top (Lambda puts /var/task on sys.path), bytecode precompiled for the runtime's Python, since
    /var/task is read-only; the manifest alongside."""
    steps.start("zip")
    staged = stage / "lambda.zip"
    _digest, written = write_payload(p.site, staged)
    steps.start("verify")
    manifest_json = _plain_manifest(p, "lambda", written)
    steps.start("write")
    with zipfile.ZipFile(staged, "a") as zf:
        info = zipfile.ZipInfo(DIR_MANIFEST, FIXED_TIME)
        info.external_attr = 0o100644 << 16
        info.compress_type = zipfile.ZIP_DEFLATED
        zf.writestr(info, manifest_json)
    return staged
